#ifndef PHOENIX_FREE_TYPE_INCLUDES_H
#define PHOENIX_FREE_TYPE_INCLUDES_H

#define PHOENIX_FREE_TYPE_AVAILABLE 0
#if PHOENIX_FREE_TYPE_AVAILABLE
#	include "FreeType/ft2build.h"
#	include FT_FREETYPE_H
#endif

#endif
